---
title: "Project"
author: "ElgunIsmayilov"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(xts)
```

```{r data}
load("/Users/elgun/Desktop/Quantitative-strategies-on-High-Frequency-Data/data/data1_2024_Q1.RData")
load("/Users/elgun/Desktop/Quantitative-strategies-on-High-Frequency-Data/data/data1_2024_Q2.RData")
load("/Users/elgun/Desktop/Quantitative-strategies-on-High-Frequency-Data/data/data1_2023_Q2.RData")
load("/Users/elgun/Desktop/Quantitative-strategies-on-High-Frequency-Data/data/data1_2023_Q4.RData")
load("/Users/elgun/Desktop/Quantitative-strategies-on-High-Frequency-Data/data/data1_2022_Q4.RData")
load("/Users/elgun/Desktop/Quantitative-strategies-on-High-Frequency-Data/data/data1_2022_Q3.RData")
load("/Users/elgun/Desktop/Quantitative-strategies-on-High-Frequency-Data/data/data1_2022_Q1.RData")

```

```{r}
data1_2022_Q1$time <- strptime(data1_2022_Q1$time, 
                                  format = "%d.%m.%Y %H:%M:%OS",
                                  tz = "GMT")
```

```{r}
plot(data1_2022_Q1[,1])
```

```{r}
data1_2022_Q3$time <- strptime(data1_2022_Q3$time, 
                                  format = "%d.%m.%Y %H:%M:%OS",
                                  tz = "GMT")
```

```{r}
plot(data1_2022_Q3[,1])
```

```{r}
data1_2022_Q4$time <- strptime(data1_2022_Q4$time, 
                                  format = "%d.%m.%Y %H:%M:%OS",
                                  tz = "GMT")
```

```{r}
plot(data1_2022_Q4[,1])
```

```{r}
data1_2023_Q2$time <- strptime(data1_2023_Q2$time, 
                                  format = "%d.%m.%Y %H:%M:%OS",
                                  tz = "GMT")
```

```{r}
plot(data1_2023_Q2[,1])
```

```{r}
data1_2023_Q4$time <- strptime(data1_2023_Q4$time, 
                                  format = "%d.%m.%Y %H:%M:%OS",
                                  tz = "GMT")
```

```{r}
plot(data1_2023_Q4[,1])
```

```{r}
data1_2024_Q1$time <- strptime(data1_2024_Q1$time, 
                                  format = "%d.%m.%Y %H:%M:%OS",
                                  tz = "GMT")
```

```{r}
plot(data1_2024_Q1[,1])
```

```{r}
data1_2024_Q2$time <- strptime(data1_2024_Q2$time, 
                                  format = "%d.%m.%Y %H:%M:%OS",
                                  tz = "GMT")
```

```{r}
plot(data1_2024_Q2[,1])
```

