---
title: "Project"
author: "ElgunIsmayilov"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(xts)
library(TTR)
library(ggplot2)
library(dplyr)
library(quantmod)
library(tseries)
library(PerformanceAnalytics)
library(roll)
library(chron) 
```

```{r}
source("https://raw.githubusercontent.com/ptwojcik/HFD/master/function_positionVB.R")
```

```{r data}
load("/Users/elgun/Desktop/Quantitative-strategies-on-High-Frequency-Data/data/data1_2024_Q1.RData")
load("/Users/elgun/Desktop/Quantitative-strategies-on-High-Frequency-Data/data/data1_2024_Q2.RData")
load("/Users/elgun/Desktop/Quantitative-strategies-on-High-Frequency-Data/data/data1_2023_Q2.RData")
load("/Users/elgun/Desktop/Quantitative-strategies-on-High-Frequency-Data/data/data1_2023_Q4.RData")
load("/Users/elgun/Desktop/Quantitative-strategies-on-High-Frequency-Data/data/data1_2022_Q4.RData")
load("/Users/elgun/Desktop/Quantitative-strategies-on-High-Frequency-Data/data/data1_2022_Q3.RData")
load("/Users/elgun/Desktop/Quantitative-strategies-on-High-Frequency-Data/data/data1_2022_Q1.RData")

```

```{r}
data1_2022_Q1$time <- strptime(data1_2022_Q1$time, 
                                  format = "%d.%m.%Y %H:%M:%OS",
                                  tz = "GMT")
```

```{r}
plot(data1_2022_Q1[,1])
```

```{r}
data1_2022_Q3$time <- strptime(data1_2022_Q3$time, 
                                  format = "%d.%m.%Y %H:%M:%OS",
                                  tz = "GMT")
```

```{r}
plot(data1_2022_Q3[,1])
```

```{r}
data1_2022_Q4$time <- strptime(data1_2022_Q4$time, 
                                  format = "%d.%m.%Y %H:%M:%OS",
                                  tz = "GMT")
```

```{r}
plot(data1_2022_Q4[,1])
```

```{r}
data1_2023_Q2$time <- strptime(data1_2023_Q2$time, 
                                  format = "%d.%m.%Y %H:%M:%OS",
                                  tz = "GMT")
```

```{r}
plot(data1_2023_Q2[,1])
```

```{r}
data1_2023_Q4$time <- strptime(data1_2023_Q4$time, 
                                  format = "%d.%m.%Y %H:%M:%OS",
                                  tz = "GMT")
```

```{r}
plot(data1_2023_Q4[,1])
```

```{r}
data1_2024_Q1$time <- strptime(data1_2024_Q1$time, 
                                  format = "%d.%m.%Y %H:%M:%OS",
                                  tz = "GMT")
```

```{r}
plot(data1_2024_Q1[,1])
```

```{r}
data1_2024_Q2$time <- strptime(data1_2024_Q2$time, 
                                  format = "%d.%m.%Y %H:%M:%OS",
                                  tz = "GMT")
```

```{r}
plot(data1_2024_Q2[,1])
```

```{r}
times(c("00:00:00","09:40:00", "15:50:00", "23:59:59"))

as.numeric(times(c("00:00:00","09:40:00", "15:50:00", "23:59:59")))

# easy comparisons
times("09:40:00") < times("15:50:00")
times("16:40:00") < times("9:50:00")
```


```{r}
data1_2022_Q1$ema_10 <- EMA(data1_2022_Q1$NQ, 10)
data1_2022_Q1$ema_20 <- EMA(data1_2022_Q1$NQ, 50)
```


```{r}
data1_2022_Q1$postion <- ifelse(lag.xts(data1_2022_Q1$ema_20) > lag.xts(data1_2022_Q1$ema_10), -1, 1)

```

```{r}
data1_2022_Q1$groos_profit <- data1_2022_Q1$postion * diff.xts(data1_2022_Q1$NQ) * 50
```

```{r}
data1_2022_Q1$groos_profit[is.na(data1_2022_Q1$groos_profit)] <- 0
chart_Series(cumsum(data1_2022_Q1$groos_profit),
             name = "Gross PnL for One MA entry - momentum")
```

```{r}
data1_2022_Q1$NoOfTrans <- abs(diff.xts(data1_2022_Q1$postion))
```

```{r}
data1_2022_Q1$NoOfTrans[1] <- 0
```

```{r}
data1_2022_Q1$net_profit <- data1_2022_Q1$groos_profit - data1_2022_Q1$NoOfTrans * 12
```

```{r}
#data1_2022_Q1$net_profit[is.na(data1_2022_Q1$net_profit)] <- 0
chart_Series(cumsum((data1_2022_Q1$net_profit)))
```

```{r}
data1_2022_Q1$sd_10 <- roll_sd(data1_2022_Q1$NQ, 
                               10,
                               na_restore = TRUE)
```
{
```{r}
times(c("00:00:00","09:40:00", "15:50:00", "23:59:59"))
times_data <- substr(index(data1_2022_Q1), 12, 19)
```

```{r}
# first we create column of zero's
data1_2022_Q1$sd_postion <- 0

# lets do it within a for() loop 

# sample loop - to remind you how it works

for(i in 1:10) print(i)


# for simplicity of the code
# lets create auxiliary vectors 

signal <- data1_2022_Q1$NQ
upper <- data1_2022_Q1$ema_10 + 3 * data1_2022_Q1$sd_10
lower <- data1_2022_Q1$ema_10 - 3 * data1_2022_Q1$sd_10
position <- data1_2022_Q1$sd_postion


# and calculate position for every minute

system.time({

for (i in 2:nrow(data1_2022_Q1)) { 
  # what if we are in the first or last 5 minutes of the session
  if ( times(times_data[i] ) <= times("9:40:00") | 
       times(times_data[i] ) > times("15:50:00")
     ) { position[i] <- 0 }
   else
    { # check if values are nonmissing 
      # (otherwise calculations not possible)
      if ( !is.na( signal[i-1] ) & 
           !is.na( upper[i-1] ) & 
           !is.na( lower[i-1] )
         )
      { # what if previous position was 0
        if ( position[i-1] == 0 )
          { if ( signal[i-1] > upper[i-1] ) { position[i] <- 1 }
            if ( signal[i-1] < lower[i-1] ) { position[i] <- -1 }
          } else if ( position[i-1] == 1 )
            { # what if previous position was 1
              if ( signal[i-1] > lower[i-1] ) { position[i] <- 1 }
              if ( signal[i-1] < lower[i-1] ) { position[i] <- -1 }
            } else if ( position[i-1] == -1 )
              { # what if previous position was -1
                if ( signal[i-1] < upper[i-1] ) { position[i] <- -1 }
                if ( signal[i-1] > upper[i-1] ) { position[i] <- 1 }
              }
      } else position[i] <- position[i-1]
      # if anything is missing, keep previous position
    } 
} # end of loop for i

}) # end of system.time()


```

```{r}
data1_2022_Q1$upper <- data1_2022_Q1$ema_10 + 3 * data1_2022_Q1$sd_10
data1_2022_Q1$lower <- data1_2022_Q1$ema_10 - 3 * data1_2022_Q1$sd_10
```

```{r}
system.time(
data1_2022_Q1$sd_postion <- 
  positionVB(signal <- data1_2022_Q1$NQ,
             upper <- data1_2022_Q1$ema_10 + 3 * data1_2022_Q1$sd_10,
             lower <- data1_2022_Q1$ema_10 - 3 * data1_2022_Q1$sd_10,
             times_data = times_data,  
             time_lower = "09:40:00", 
             time_upper = "15:50:00", 
             strategy = "ema"))
```

```{r}
data1_2022_Q1$groos_profit_sd <- data1_2022_Q1$sd_postion * diff.xts(data1_2022_Q1$NQ) * 50
```

```{r}
data1_2022_Q1$groos_profit_sd[is.na(data1_2022_Q1$groos_profit_sd)] <- 0
```

```{r}
chartSeries(cumsum(data1_2022_Q1$groos_profit_sd))
```

```{r}
sortino_ratio_gross <- SortinoRatio(data1_2022_Q1$groos_profit)
sortino_ratio_gross
```

```{r}
sortino_ratio_net <- SortinoRatio(data1_2022_Q1$net_profit)
sortino_ratio_net
```

```{r}
# Calmar Ratio

# definition of a new (user) function

myCalmarRatio <- function(x, # x = series of returns
                 # scale parameter = Nt
                 scale) {
  scale * mean(coredata(x), na.rm = TRUE) / 
    maxdrawdown(cumsum(x))$maxdrawdown
  
}

```

```{r}
myCalmarRatio(data1_2022_Q1$groos_profit, 
              scale = 252)
```

```{r}
myCalmarRatio(data1_2022_Q1$net_profit, scale = 252)
```

```{r}
SortinoRatio(data1_2022_Q1$groos_profit_sd)

```

```{r}
SortinoRatio()
```

```{r}
tail(data1_2022_Q1$groos_profit, 1)
```

```{r}
tail(data1_2022_Q1$net_profit,1)

```

```{r}
sapply(data1_2022_Q1[, grep("NoOfTrans", names(data1_2022_Q1))], # data
       function(x) mean(x, na.rm = TRUE) # function applied
     )
```



